# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.taskpulse.v1 import taskpulse_pb2 as proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/taskpulse/v1/taskpulse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/taskpulse.v1.HealthService/Check',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.HealthService/Check',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWorkspaces = channel.unary_unary(
                '/taskpulse.v1.WorkspaceService/ListWorkspaces',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesResponse.FromString,
                _registered_method=True)


class WorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListWorkspaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.WorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.WorkspaceService/ListWorkspaces',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAgents = channel.unary_unary(
                '/taskpulse.v1.AgentService/ListAgents',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.AgentService/ListAgents',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEvents = channel.unary_unary(
                '/taskpulse.v1.EventService/ListEvents',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.CreateEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/CreateEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
                _registered_method=True)
        self.UpdateEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/UpdateEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.UpdateEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
                _registered_method=True)
        self.DeleteEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/DeleteEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.DeleteEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Empty.FromString,
                _registered_method=True)
        self.RunEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/RunEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.RunEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Execution.FromString,
                _registered_method=True)
        self.PauseEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/PauseEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.PauseEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
                _registered_method=True)
        self.ResumeEvent = channel.unary_unary(
                '/taskpulse.v1.EventService/ResumeEvent',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ResumeEventRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
                _registered_method=True)


class EventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsResponse.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.CreateEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.SerializeToString,
            ),
            'UpdateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.UpdateEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.SerializeToString,
            ),
            'DeleteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.DeleteEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Empty.SerializeToString,
            ),
            'RunEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.RunEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Execution.SerializeToString,
            ),
            'PauseEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.PauseEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.SerializeToString,
            ),
            'ResumeEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeEvent,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ResumeEventRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/ListEvents',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/CreateEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.CreateEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/UpdateEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.UpdateEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/DeleteEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.DeleteEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/RunEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.RunEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/PauseEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.PauseEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.EventService/ResumeEvent',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ResumeEventRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExecutionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListExecutions = channel.unary_unary(
                '/taskpulse.v1.ExecutionService/ListExecutions',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutions,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.ExecutionService/ListExecutions',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/taskpulse.v1.ToolService/ListTools',
                request_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsRequest.FromString,
                    response_serializer=proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskpulse.v1.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskpulse.v1.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskpulse.v1.ToolService/ListTools',
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsRequest.SerializeToString,
            proto_dot_taskpulse_dot_v1_dot_taskpulse__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
